### ISSUE TITLE
Release 1.4.1

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#234]
Checklist for releasing v1.4.1: 

- [x] Bump version in `__init__.py` in `hotfix` (#235)
- [x] Add changelog for v1.4.0 in `hotfix` (#235)
- [x] Add new contributors to v1.4.1 (#235)
- [x] Merge `hotfix` into `main` (#237)
- [x] Merge `main` into `RC_v1.5.0`
- [x] Delete branch `hotfix`
- [x] Create release
- [x] Push release to conda-forge
- [x] E-mail tobac mailing list

**Comment by w-k-jones** [comment]
conda-forge PR: https://github.com/conda-forge/tobac-feedstock/pull/19

Just waiting for all checks and re-rendering to finish

**Comment by w-k-jones** [comment]
All tasks finished, new version is available on conda
