### ISSUE TITLE
Release v1.5.0

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#307]
Checklist for releasing v1.5.0:

* [x]  Merge #300 
* [x] Re-run notebooks and commit updates to repository (#286; #308)
* [x]  Bump version in `__init__.py `in `RC_v1.5.0` 
* [x]  Add changelog in `RC_v1.5.0`  (#309)
* [x]  Merge `RC_v1.5.0` into `main` (#311)
* [ ]  Delete `RC_v1.5.0` branch
* [x]  Create release
* [x]  Push release to conda-forge 
* [x]  E-mail tobac mailing list

**Comment by w-k-jones** [comment]
Notebooks re-generated in #308

**Comment by freemansw1** [comment]
#311 merges into main (I wanted to write some hopefully nice acknowledgements somewhere, seemed appropriate there)
