### ISSUE TITLE
Release v1.5.1

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#324]
Checklist for releasing v1.5.1:

* [x] Re-run notebooks and commit updates to repository (#325)
* [x]  Bump version in `__init__.py `in `RC_v1.5_hotfix` (#325)
* [x]  Add changelog in `RC_v1.5_hotfix` (#325)
* [x]  Merge `RC_v1.5_hotfix` into `main` (#323)
* [x]  Delete `RC_v1.5_hotfix` branch
* [x]  Create release
* [x]  Push release to conda-forge 
* [x]  E-mail tobac mailing list
